[package]
name = "tari_chat_ffi"
authors = ["The Tari Development Community"]
description = "Tari chat interface FFI bindings"
license = "BSD-3-Clause"
version = "0.49.0-pre.0"
edition = "2018"

[dependencies]
tari_core = {  path = "../../base_layer/core", default-features = false, features = ["tari_mmr", "transactions"] }
tari_comms = {  path = "../../comms/core", features = ["c_integration"]}
tari_contacts = { path = "../../base_layer/contacts" }

[target.'cfg(target_os="android")'.dependencies]
openssl = { version = "0.10.41", features = ["vendored"] }

[lib]
crate-type = ["staticlib","cdylib"]

[dev-dependencies]

[build-dependencies]
cbindgen = "0.24.3"
tari_common = { path = "../../common", features = ["build", "static-application-info"] }
